name: Test

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
        
    - name: Install pytest
      run: pip install pytest

    - name: Install flake8
      run: pip install flake8

    - name: Run tests
      run: pytest lab1.py
      
    - name: Lint code
      run: flake8 lab1.py

