name: Fucking pipeline

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        pip install pytest
        pip install flake8

    - name: Run Python tests
      run: pytest your_folder_with_tests/*.py

    - name: Run Go tests
      run: go test ./your_folder_with_tests/...

    - name: Run linting
      run: |
        flake8 . --exit-zero
