name: Go Test in Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Go tests in Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t go-tests ./Lab4

    - name: Run tests in Docker container
      run: docker run go-tests
